// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringAndEvaluationPlatform.Data;

#nullable disable

namespace MonitoringAndEvaluationPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommunityProject", b =>
                {
                    b.Property<string>("CommunitiesCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("projectsProjectID")
                        .HasColumnType("int");

                    b.HasKey("CommunitiesCode", "projectsProjectID");

                    b.HasIndex("projectsProjectID");

                    b.ToTable("ProjectCommunities", (string)null);
                });

            modelBuilder.Entity("DistrictProject", b =>
                {
                    b.Property<string>("DistrictsCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("projectsProjectID")
                        .HasColumnType("int");

                    b.HasKey("DistrictsCode", "projectsProjectID");

                    b.HasIndex("projectsProjectID");

                    b.ToTable("ProjectDistricts", (string)null);
                });

            modelBuilder.Entity("DonorProject", b =>
                {
                    b.Property<int>("DonorsCode")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsProjectID")
                        .HasColumnType("int");

                    b.HasKey("DonorsCode", "ProjectsProjectID");

                    b.HasIndex("ProjectsProjectID");

                    b.ToTable("DonorProject");
                });

            modelBuilder.Entity("GovernorateProject", b =>
                {
                    b.Property<string>("GovernoratesCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("projectsProjectID")
                        .HasColumnType("int");

                    b.HasKey("GovernoratesCode", "projectsProjectID");

                    b.HasIndex("projectsProjectID");

                    b.ToTable("ProjectGovernorates", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MinistryProject", b =>
                {
                    b.Property<int>("MinistriesCode")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsProjectID")
                        .HasColumnType("int");

                    b.HasKey("MinistriesCode", "ProjectsProjectID");

                    b.HasIndex("ProjectsProjectID");

                    b.ToTable("ProjectMinistries", (string)null);
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ActionPlan", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<int>("PlansCount")
                        .HasColumnType("int");

                    b.Property<int>("ProjectPhaseId")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("ProjectPhaseId")
                        .IsUnique();

                    b.ToTable("ActionPlans");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MinistryCode")
                        .HasColumnType("int");

                    b.Property<string>("MinistryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MinistryCode");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Community", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AR_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EN_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDistrictCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Code");

                    b.HasIndex("SubDistrictCode");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.CurrencyRate", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RateToSyp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("CurrencyRates");

                    b.HasData(
                        new
                        {
                            Code = "SYP",
                            NameAr = "ليرة سورية",
                            NameEn = "Syrian Pound",
                            RateToSyp = 1m,
                            Symbol = "SYP ",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "USD",
                            NameAr = "دولار أمريكي",
                            NameEn = "US Dollar",
                            RateToSyp = 13000m,
                            Symbol = "$",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Code = "EUR",
                            NameAr = "يورو",
                            NameEn = "Euro",
                            RateToSyp = 14000m,
                            Symbol = "€",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.District", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EN_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovernorateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Code");

                    b.HasIndex("GovernorateCode");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Donor", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.Property<bool>("IsInvestmentBudget")
                        .HasColumnType("bit");

                    b.Property<string>("Partner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("donorCategory")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Framework", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.Property<int?>("MinistryCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("MinistryCode");

                    b.ToTable("Frameworks");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("BaseValueForCurrentYear")
                        .HasColumnType("float");

                    b.Property<double>("BaseValueForStartingYear")
                        .HasColumnType("float");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("int");

                    b.Property<int>("FrameworkCode")
                        .HasColumnType("int");

                    b.Property<int>("GoalType")
                        .HasColumnType("int");

                    b.Property<bool>("ManualYearlyTargets")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartingYear")
                        .HasColumnType("int");

                    b.Property<double>("TargetValue")
                        .HasColumnType("float");

                    b.Property<int>("TargetYear")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("FrameworkCode");

                    b.ToTable("FrameworkGoals");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrameworkGoalID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkGoalID");

                    b.ToTable("FrameworkGoalFiles");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoalManualExpectedTarget", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("ExpectedTargetValue")
                        .HasColumnType("float");

                    b.Property<int>("FrameworkGoalID")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FrameworkGoalID", "Year")
                        .IsUnique();

                    b.ToTable("FrameworkGoalManualExpectedTargets");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoalYearlyValue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("ActualValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrameworkGoalID")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FrameworkGoalID", "Year")
                        .IsUnique();

                    b.ToTable("FrameworkGoalYearlyValues");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Goal", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("AR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<string>("EN_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Governorate", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EN_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Governorates");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.GuideSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("SectionKey")
                        .IsUnique();

                    b.ToTable("GuideSections");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.GuideSectionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuideSectionId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SavedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GuideSectionId");

                    b.ToTable("GuideSectionVersions");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Indicator", b =>
                {
                    b.Property<int>("IndicatorCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndicatorCode"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<double>("GAGRA")
                        .HasColumnType("float");

                    b.Property<double>("GAGRR")
                        .HasColumnType("float");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.Property<bool>("IsCommon")
                        .HasColumnType("bit");

                    b.Property<string>("MethodOfComputation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubOutputCode")
                        .HasColumnType("int");

                    b.Property<int>("Target")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetYear")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("IndicatorCode");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SubOutputCode");

                    b.ToTable("Indicators");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Measure", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeasureType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProjectPhaseId")
                        .HasColumnType("int");

                    b.Property<double?>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.HasIndex("ProjectPhaseId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.MeasureFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeasureCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasureCode");

                    b.ToTable("MeasureFiles");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Ministry", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinistryDisplayName_AR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinistryDisplayName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinistryUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Ministries");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Outcome", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<int>("FrameworkCode")
                        .HasColumnType("int");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.HasIndex("FrameworkCode");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Output", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutcomeCode")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.HasIndex("OutcomeCode");

                    b.ToTable("Outputs");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Plan", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<int>("ActionPlanCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Realised")
                        .HasColumnType("bigint");

                    b.HasKey("Code");

                    b.HasIndex("ActionPlanCode");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.PlatformVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("VersionNumber")
                        .IsUnique();

                    b.ToTable("PlatformVersions");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("BudgetUnit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("EstimatedBudget")
                        .HasColumnType("float");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("ExchangeRateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GoalCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsEntireCountry")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MinistryCode")
                        .HasColumnType("int");

                    b.Property<int>("ProjectManagerCode")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PublicSectorTypeCode")
                        .HasColumnType("int");

                    b.Property<double>("RealBudget")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuperVisorCode")
                        .HasColumnType("int");

                    b.Property<double>("performance")
                        .HasColumnType("float");

                    b.HasKey("ProjectID");

                    b.HasIndex("GoalCode");

                    b.HasIndex("MinistryCode");

                    b.HasIndex("ProjectManagerCode");

                    b.HasIndex("PublicSectorTypeCode");

                    b.HasIndex("SuperVisorCode");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ProjectDonor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonorCode")
                        .HasColumnType("int");

                    b.Property<decimal>("FundingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FundingPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorCode");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectDonors");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ProjectFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ProjectManager", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("ProjectManagers");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ProjectPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("PhasePerformance")
                        .HasColumnType("float");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TargetQuantity")
                        .HasColumnType("float");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectPhases");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.PublicSectorType", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("AR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EN_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("PublicSectorTypes");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MinistryCode")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PlatformVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequestingParty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("MinistryCode");

                    b.HasIndex("PlatformVersionId");

                    b.HasIndex("RequestEmployeeId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OnBehalfOfEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("OnBehalfOfEmployeeId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestComments");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestCommentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestCommentId");

                    b.ToTable("RequestCommentAttachments");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RequestEmployees");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestFiles");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecordedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequestEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("RequestEmployeeId");

                    b.HasIndex("RequestId", "RequestEmployeeId")
                        .IsUnique();

                    b.ToTable("RequestTests");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SDGIndicator", b =>
                {
                    b.Property<int>("IndicatorCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndicatorCode"));

                    b.Property<string>("AR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<string>("EN_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.Property<bool>("IsCommon")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetCode")
                        .HasColumnType("int");

                    b.HasKey("IndicatorCode");

                    b.HasIndex("TargetCode");

                    b.ToTable("sDGIndicators");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Sector", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("AR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<string>("EN_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SubDistrict", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EN_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("DistrictCode");

                    b.ToTable("SubDistricts");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SubOutput", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutputCode")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.HasIndex("OutputCode");

                    b.ToTable("SubOutputs");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SuperVisor", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("SuperVisors");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Target", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("AR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisbursementPerformance")
                        .HasColumnType("float");

                    b.Property<string>("EN_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoalCode")
                        .HasColumnType("int");

                    b.Property<double>("IndicatorsPerformance")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.HasIndex("GoalCode");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("ProjectSector", b =>
                {
                    b.Property<int>("ProjectsProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SectorsCode")
                        .HasColumnType("int");

                    b.HasKey("ProjectsProjectID", "SectorsCode");

                    b.HasIndex("SectorsCode");

                    b.ToTable("ProjectSectors", (string)null);
                });

            modelBuilder.Entity("ProjectSubDistrict", b =>
                {
                    b.Property<string>("SubDistrictsCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("projectsProjectID")
                        .HasColumnType("int");

                    b.HasKey("SubDistrictsCode", "projectsProjectID");

                    b.HasIndex("projectsProjectID");

                    b.ToTable("ProjectSubDistricts", (string)null);
                });

            modelBuilder.Entity("CommunityProject", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Community", null)
                        .WithMany()
                        .HasForeignKey("CommunitiesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("projectsProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DistrictProject", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("projectsProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DonorProject", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Donor", null)
                        .WithMany()
                        .HasForeignKey("DonorsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GovernorateProject", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Governorate", null)
                        .WithMany()
                        .HasForeignKey("GovernoratesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("projectsProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinistryProject", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Ministry", null)
                        .WithMany()
                        .HasForeignKey("MinistriesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ActionPlan", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ProjectPhase", "ProjectPhase")
                        .WithOne("ActionPlan")
                        .HasForeignKey("MonitoringAndEvaluationPlatform.Models.ActionPlan", "ProjectPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectPhase");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ApplicationUser", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryCode");

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Community", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.SubDistrict", "SubDistrict")
                        .WithMany("Communities")
                        .HasForeignKey("SubDistrictCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubDistrict");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.District", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Governorate", "Governorate")
                        .WithMany("Districts")
                        .HasForeignKey("GovernorateCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Framework", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryCode");

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoal", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Framework", "Framework")
                        .WithMany("Goals")
                        .HasForeignKey("FrameworkCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoalFile", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.FrameworkGoal", "FrameworkGoal")
                        .WithMany("Attachments")
                        .HasForeignKey("FrameworkGoalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrameworkGoal");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoalManualExpectedTarget", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.FrameworkGoal", "FrameworkGoal")
                        .WithMany("ManualExpectedTargets")
                        .HasForeignKey("FrameworkGoalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrameworkGoal");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoalYearlyValue", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.FrameworkGoal", "FrameworkGoal")
                        .WithMany("YearlyValues")
                        .HasForeignKey("FrameworkGoalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrameworkGoal");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.GuideSectionVersion", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.GuideSection", "GuideSection")
                        .WithMany("Versions")
                        .HasForeignKey("GuideSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuideSection");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Indicator", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", "Project")
                        .WithMany("Indicators")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.SubOutput", "SubOutput")
                        .WithMany("Indicators")
                        .HasForeignKey("SubOutputCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SubOutput");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Measure", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ProjectPhase", "ProjectPhase")
                        .WithMany("Measures")
                        .HasForeignKey("ProjectPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectPhase");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.MeasureFile", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Measure", "Measure")
                        .WithMany("Files")
                        .HasForeignKey("MeasureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Outcome", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Framework", "Framework")
                        .WithMany("Outcomes")
                        .HasForeignKey("FrameworkCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Output", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Outcome", "Outcome")
                        .WithMany("Outputs")
                        .HasForeignKey("OutcomeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outcome");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Plan", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ActionPlan", "ActionPlan")
                        .WithMany("Plans")
                        .HasForeignKey("ActionPlanCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionPlan");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Project", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalCode");

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryCode");

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ProjectManager", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.PublicSectorType", "PublicSectorType")
                        .WithMany("Projects")
                        .HasForeignKey("PublicSectorTypeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.SuperVisor", "SuperVisor")
                        .WithMany()
                        .HasForeignKey("SuperVisorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Ministry");

                    b.Navigation("ProjectManager");

                    b.Navigation("PublicSectorType");

                    b.Navigation("SuperVisor");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ProjectDonor", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Donor", "Donor")
                        .WithMany("ProjectDonors")
                        .HasForeignKey("DonorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", "Project")
                        .WithMany("ProjectDonors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ProjectFile", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", "Project")
                        .WithMany("ProjectFiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ProjectPhase", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", "Project")
                        .WithMany("Phases")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Request", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ApplicationUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.PlatformVersion", "PlatformVersion")
                        .WithMany("Requests")
                        .HasForeignKey("PlatformVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.RequestEmployee", "RequestEmployee")
                        .WithMany("Requests")
                        .HasForeignKey("RequestEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ApplicationUser", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Ministry");

                    b.Navigation("PlatformVersion");

                    b.Navigation("RequestEmployee");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestComment", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ApplicationUser", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.RequestEmployee", "OnBehalfOfEmployee")
                        .WithMany()
                        .HasForeignKey("OnBehalfOfEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.RequestComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Request", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("OnBehalfOfEmployee");

                    b.Navigation("ParentComment");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestCommentAttachment", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.RequestComment", "RequestComment")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestComment");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestFile", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Request", "Request")
                        .WithMany("Files")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestTest", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.ApplicationUser", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.RequestEmployee", "RequestEmployee")
                        .WithMany("Tests")
                        .HasForeignKey("RequestEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Request", "Request")
                        .WithMany("Tests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordedByUser");

                    b.Navigation("Request");

                    b.Navigation("RequestEmployee");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SDGIndicator", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Target", "Target")
                        .WithMany("SDGsIndicators")
                        .HasForeignKey("TargetCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SubDistrict", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.District", "District")
                        .WithMany("SubDistricts")
                        .HasForeignKey("DistrictCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SubOutput", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Output", "Output")
                        .WithMany("SubOutputs")
                        .HasForeignKey("OutputCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Output");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Target", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Goal", "Goal")
                        .WithMany("Targets")
                        .HasForeignKey("GoalCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("ProjectSector", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSubDistrict", b =>
                {
                    b.HasOne("MonitoringAndEvaluationPlatform.Models.SubDistrict", null)
                        .WithMany()
                        .HasForeignKey("SubDistrictsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringAndEvaluationPlatform.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("projectsProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ActionPlan", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.District", b =>
                {
                    b.Navigation("SubDistricts");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Donor", b =>
                {
                    b.Navigation("ProjectDonors");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Framework", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.FrameworkGoal", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ManualExpectedTargets");

                    b.Navigation("YearlyValues");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Goal", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Governorate", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.GuideSection", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Measure", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Outcome", b =>
                {
                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Output", b =>
                {
                    b.Navigation("SubOutputs");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.PlatformVersion", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Project", b =>
                {
                    b.Navigation("Indicators");

                    b.Navigation("Phases");

                    b.Navigation("ProjectDonors");

                    b.Navigation("ProjectFiles");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.ProjectPhase", b =>
                {
                    b.Navigation("ActionPlan");

                    b.Navigation("Measures");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.PublicSectorType", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Request", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Files");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestComment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.RequestEmployee", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SubDistrict", b =>
                {
                    b.Navigation("Communities");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.SubOutput", b =>
                {
                    b.Navigation("Indicators");
                });

            modelBuilder.Entity("MonitoringAndEvaluationPlatform.Models.Target", b =>
                {
                    b.Navigation("SDGsIndicators");
                });
#pragma warning restore 612, 618
        }
    }
}
