//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringAndEvaluationPlatform.Resources.Models {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Project {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Project() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitoringAndEvaluationPlatform.Resources.Models.Project", typeof(Project).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End date is required.
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Estimated budget must be greater than $0.01.
        /// </summary>
        public static string EstimatedBudgetRange {
            get {
                return ResourceManager.GetString("EstimatedBudgetRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Estimated budget is required.
        /// </summary>
        public static string EstimatedBudgetRequired {
            get {
                return ResourceManager.GetString("EstimatedBudgetRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project manager is required.
        /// </summary>
        public static string ProjectManagerRequired {
            get {
                return ResourceManager.GetString("ProjectManagerRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project name must be between 3 and 200 characters.
        /// </summary>
        public static string ProjectNameLength {
            get {
                return ResourceManager.GetString("ProjectNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project name is required.
        /// </summary>
        public static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Real budget cannot be negative.
        /// </summary>
        public static string RealBudgetRange {
            get {
                return ResourceManager.GetString("RealBudgetRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start date is required.
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supervisor is required.
        /// </summary>
        public static string SupervisorRequired {
            get {
                return ResourceManager.GetString("SupervisorRequired", resourceCulture);
            }
        }
    }
}
